services:
  build-otp:
    image: docker.io/opentripplanner/opentripplanner:latest
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx8g
    volumes:
      - ./data/shared:/var/opentripplanner
    command: --build --save
    deploy:
      resources:
        limits:
          memory: 8g
    container_name: build_otp
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/opentripplanner/graph.obj"]
      interval: 10s
      retries: 10
      start_period: 30s
  
  serve-otp:
    image: docker.io/opentripplanner/opentripplanner:latest
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx8g
    volumes:
      - ./data/shared:/var/opentripplanner
    ports:
      - ${OTP_PORT}:8080
    command: --load --serve
    deploy:
      resources:
        limits:
          memory: 8g
    depends_on:
      build-otp:
        condition: service_healthy
    container_name: serve_otp
    restart: unless-stopped

  # MERGED_gtfs.zip is hardcoded here.
  # You probably do not need the ./data/valhalla:/custom_files
  valhalla:
    image: ghcr.io/valhalla/valhalla-scripted:latest
    container_name: valhalla
    environment:
      - build_transit=False
      - build_time_zones=True
      - build_admins=True
      - traffic_name=""
      - build_tar=True
    volumes:
      - ./data/valhalla:/custom_files
      - ./data/shared/MERGED_gtfs:/gtfs_feeds/gtfs
    restart: unless-stopped
    ports:
      - ${VALHALLA_PORT}:8002

  vroom:
    image: ghcr.io/vroom-project/vroom-docker:v1.14.0
    container_name: vroom
    environment:
      - VROOM_ROUTER=${VROOM_ROUTER}
    volumes:
      - ./data/vroom:/conf
    ports:
      - ${VROOM_PORT}:3000
    depends_on:
      - osrm
      - valhalla

  osrm:
    image: ghcr.io/project-osrm/osrm-backend:v6.0.0
    container_name: osrm
    volumes:
      - ./data/osrm:/data
      - ./data/osrm/car.lua:/opt/car.lua
    command: >
      sh -c "if [ ! -f /data/${OSRM_BASE}.osrm.cells ] ; then
               osrm-extract -p /opt/car.lua /data/${OSRM_PBF} &&
               osrm-partition /data/${OSRM_BASE}.osrm &&
               osrm-customize /data/${OSRM_BASE}.osrm &&
               osrm-contract /data/${OSRM_BASE}.osrm --segment-speed-file /data/${SPEED_CSV};
             fi &&
             osrm-routed --algorithm mld --max-alternatives 10 --max-table-size=10000 /data/${OSRM_BASE}.osrm"
    environment:
      - OSRM_PBF=tn.osm.pbf
      - OSRM_BASE=tn
      - SPEED_CSV=speeds.csv
    ports:
      - ${OSRM_PORT}:5000
    deploy:
      resources:
        limits:
          memory: 4g  # Adjust memory limit as needed
    restart: unless-stopped
    
